name: alpine

on:
  schedule:
    # 每半年7号，4:00执行一次，以同步官方
    - cron: '0 4 7 */6 *'
  push:
    #branches: [ master ]
    paths:
    - Dockerfile.alpine
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # 设置 QEMU 以支持多个平台
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # 设置 buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # 登录 dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 编译并推送到 dockerhub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ryjer/torrust-actix:v4.0.8
            ryjer/torrust-actix:alpine
            ryjer/torrust-actix:latest
      
